import { _electron as electron } from 'playwright-core'
import { rmSync, mkdirSync, existsSync, readdirSync } from 'fs'
import path from 'path'

const DATA = '/tmp/bt-e2e-data'
const SHOTS = process.env.SHOTS || '/tmp/bt-shots'
if (!process.env.KEEP) rmSync(DATA, { recursive: true, force: true })
mkdirSync(SHOTS, { recursive: true })
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

const app = await electron.launch({
  executablePath: path.resolve('node_modules/electron/dist/electron'),
  args: ['--no-sandbox', '.'],
  env: { ...process.env, BRIGHTTERM_DATA: DATA, ELECTRON_ENABLE_LOGGING: '1' }
})
const win = await app.firstWindow()
win.on('console', (m) => { if (m.type() === 'error') console.log('[renderer]', m.text()) })
win.on('pageerror', (e) => console.log('[pageerror]', e.message))
await win.setViewportSize({ width: 1440, height: 880 }).catch(() => {})
const shot = async (n) => { await win.screenshot({ path: `${SHOTS}/${n}.png` }); console.log('shot', n) }
const step = (s) => console.log('==', s)

step('setup vault')
await win.waitForSelector('.lock-card')
await shot('01-setup')
await win.fill('input[placeholder^="마스터 비밀번호"]', 'MasterPass!2026')
await win.fill('input[placeholder="비밀번호 확인"]', 'MasterPass!2026')
await win.click('button:has-text("볼트 만들기")')
await win.waitForSelector('.recovery', { timeout: 20000 })
await shot('02-recovery')
await win.check('input[type=checkbox]')
await win.click('button:has-text("시작하기")')
await win.waitForSelector('.welcome')
await sleep(500)
// close import dialog if it popped
if (await win.$('.modal')) await win.keyboard.press('Escape')

step('create folder + host')
await win.click('.sb-actions button:has-text("폴더")')
await win.fill('.modal input.input', '헤펠레코리아')
await win.click('.modal .seg button:has-text("운영")')
await win.click('.modal button:has-text("저장")')
await sleep(200)

await win.click('.sb-actions button:has-text("서버")')
await win.fill('input[placeholder="예: 운영-WEB01"]', '운영-WEB01')
await win.fill('input[placeholder^="10.0.0.11"]', 'tester@127.0.0.1:2222')
await win.selectOption('.modal select.select >> nth=0', { label: '헤펠레코리아' })
await win.click('.mtabs button:has-text("인증")')
await win.fill('input[type=password][placeholder="비밀번호"]', 'Test1234!')
await shot('03-host-editor')
await win.click('button:has-text("저장 후 연결")')

step('hostkey')
await win.waitForSelector('button:has-text("신뢰하고 접속")', { timeout: 15000 })
await shot('04-hostkey')
await win.click('button:has-text("신뢰하고 접속")')
await win.waitForSelector('.pane .dot.connected', { timeout: 15000 })
await sleep(1200)
await win.keyboard.type('echo BT_OK_$((6*7)) > /tmp/bt_e2e_1; uname -a\n')
await sleep(800)
await shot('05-connected')
console.log('remote file:', existsSync('/tmp/bt_e2e_1'))

step('second host (dev)')
await win.click('.sb-actions button:has-text("서버")')
await win.fill('input[placeholder="예: 운영-WEB01"]', '개발-API')
await win.fill('input[placeholder^="10.0.0.11"]', 'tester@127.0.0.1:2222')
await win.click('.modal .seg button:has-text("개발")')
await win.click('.mtabs button:has-text("인증")')
await win.fill('input[type=password][placeholder="비밀번호"]', 'Test1234!')
await win.click('button:has-text("저장")>>nth=0')
await sleep(300)

step('split right with dev host via quick connect ctrl+enter')
await win.keyboard.press('Control+k')
await win.waitForSelector('.palette')
await win.keyboard.type('개발')
await sleep(200)
await shot('06-quick')
await win.keyboard.press('Control+Enter')
await win.waitForFunction(() => document.querySelectorAll('.pane .dot.connected').length >= 2, null, { timeout: 15000 })
await sleep(1000)
await win.keyboard.type('htop 2>/dev/null || top -b -n1 | head -20\n')
await sleep(1200)

step('image paste (Claude CLI flow)')
// put an image on the clipboard from the main process
await app.evaluate(async ({ clipboard, nativeImage }) => {
  const img = nativeImage.createFromPath('/tmp/bt-test.png')
  clipboard.clear()
  clipboard.writeImage(img)
  return { empty: clipboard.readImage().isEmpty(), formats: clipboard.availableFormats() }
}).then((r) => console.log('clipboard:', JSON.stringify(r)))
await win.keyboard.press('q')
await sleep(300)
await win.keyboard.type('clear; file ')
await win.keyboard.press('Control+v')
await sleep(2000)
await win.keyboard.press('Enter')
await sleep(900)
await shot('07-image-paste')
const up = '/home/tester/.brightterm/uploads'
console.log('uploads:', existsSync(up) ? readdirSync(up) : 'none')

step('sftp panel')
await win.keyboard.press('Control+Shift+S')
await win.waitForSelector('.sftp-row:not(.sftp-head)', { timeout: 10000 })
await sleep(500)
await shot('08-sftp')

step('dangerous guard on prod pane')
// focus first pane (prod)
await win.click('.pane >> nth=0')
await win.keyboard.type('reboot')
await win.keyboard.press('Enter')
await win.waitForSelector('.modal:has-text("위험 명령")', { timeout: 5000 })
await shot('09-guard')
await win.click('.modal button:has-text("취소")')
await win.keyboard.press('Control+u')

step('context menu + settings')
await win.click('.node:has-text("운영-WEB01")', { button: 'right' })
await sleep(200)
await shot('10-context')
await win.keyboard.press('Escape')
await win.click('.tb-right button[title="설정"]')
await win.click('.settings nav button:has-text("이미지")')
await sleep(200)
await shot('11-settings')
await win.keyboard.press('Escape')

step('light theme')
await app.evaluate(() => {})
await win.keyboard.press('Control+k')
await win.waitForSelector('.palette input')
await win.keyboard.type('>테마')
await sleep(150)
await win.keyboard.press('Enter')
await sleep(700)
await shot('12-light')
await win.keyboard.press('Control+k')
await win.waitForSelector('.palette input')
await win.keyboard.type('>테마')
await sleep(150)
await win.keyboard.press('Enter')
await sleep(300)

step('auto reconnect')
const { execSync } = await import('child_process')
execSync("pkill -KILL -u tester || true")
await win.waitForSelector('.pane .dot.reconnecting, .pane .dot.closed', { timeout: 8000 })
await shot('14-dropped')
await win.waitForFunction(() => document.querySelectorAll('.pane .dot.connected').length >= 2, null, { timeout: 30000 })
console.log('reconnected ok')
await sleep(800)
await shot('15-reconnected')

step('lock/unlock')
await win.keyboard.press('Escape'); await sleep(400); await win.click('.statusbar .sb-btn')
await win.waitForSelector('.lock-card')
await sleep(300)
await shot('13-locked')
await win.fill('.lock-card input[type=password]', 'wrong')
await win.keyboard.press('Enter')
await win.waitForSelector('.err')
await win.fill('.lock-card input[type=password]', 'MasterPass!2026')
await win.keyboard.press('Enter')
await win.waitForSelector('.lock-card', { state: 'detached', timeout: 20000 })
console.log('unlocked ok')

await app.evaluate(({ BrowserWindow }) => { BrowserWindow.getAllWindows()[0].destroy() })
await app.close().catch(() => {})
console.log('DONE')
